# This configuration defines a single web service (FastAPI backend)
# and uses a custom build script to compile and serve the Vue frontend
# alongside the Python application, resolving the "unknown type" error.

services:
  - type: web
    name: wotnot-ai-crm
    
    # Render will use the root directory as the build context for simplicity.
    rootDir: .
    
    env: python
    
    # 1. Custom Build Command: Installs Node, builds Vue, then installs Python.
    # We rely on a custom script to handle the Python/Node compilation sequence.
    buildCommand: "./build.sh"
    
    # 2. Start Command: Starts the Uvicorn server.
    startCommand: "uvicorn backend.wati.main:app --host 0.0.0.0 --port $PORT"
    
    # 3. Static File Path: Points to the final compiled assets from the Vue build.
    # This tells Render to serve these files from the root URL.
    staticPublishPath: ./frontend/my-vue-app/dist
    
    # Environment Variables
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3 
      - key: GEMINI_API_KEY
        sync: false 
      - key: DATABASE_URL 
        sync: false 
      
      # Tell the frontend where the backend API is (relative path works best on Render)
      - key: VUE_APP_API_URL 
        value: /api
