# This configuration defines two separate services:
# 1. The Dynamic Python Backend (FastAPI)
# 2. The Static Frontend (Vue.js build assets)

services:
  # ----------------------------------------------------
  # 1. DYNAMIC WEB SERVICE (FastAPI Backend)
  # ----------------------------------------------------
  - type: web
    name: wotnot-backend
    
    # Path to the directory containing your Python code
    rootDir: ./backend
    
    env: python
    buildCommand: "pip install -r requirements.txt"
    
    # This command starts your server.
    startCommand: "uvicorn wati.main:app --host 0.0.0.0 --port $PORT"
    
    # Environment Variables (Set these securely in the Render dashboard)
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3 
      - key: GEMINI_API_KEY
        sync: false 
      - key: DATABASE_URL 
        sync: false 
        
  # ----------------------------------------------------
  # 2. STATIC SITE SERVICE (Vue.js Frontend)
  # ----------------------------------------------------
  - type: static
    name: wotnot-frontend
    
    # Path to the directory containing your package.json
    rootDir: ./frontend/my-vue-app 
    
    # Command to compile the Vue application (creates the final /dist folder)
    buildCommand: "npm install && npm run build"
    
    # The directory where Vue places the final static files to be served
    # This MUST be relative to the rootDir (./frontend/my-vue-app)
    publishPath: ./dist
    
    # This environment variable tells the compiled Vue app where the backend is.
    # Render automatically handles the proxying from the frontend to the backend service.
    envVars:
      - key: VUE_APP_API_URL
        value: /api 
