# This file defines the single service (the Python backend)
# and uses a custom script to prepare the Vue frontend assets.

services:
  - type: web
    name: wotnot-backend
    
    # Path to the directory containing the build files (the wotnot root folder)
    rootDir: .
    
    # Environment is Python, but the build step handles Node/Vue compilation
    env: python
    
    # CRITICAL: This build command runs the custom script to build the Vue frontend first,
    # then installs Python dependencies.
    buildCommand: "./build.sh"
    
    # This command starts your Uvicorn server, serving all requests.
    startCommand: "uvicorn wati.main:app --host 0.0.0.0 --port $PORT"
    
    # IMPORTANT: Static files built by Vue must be served from here.
    # We assume the build.sh script moves the assets to a directory called 'static' 
    # (or you will need to configure FastAPI to serve from the 'dist' folder).
    staticPublishPath: ./frontend/my-vue-app/dist
    
    # Environment Variables - You must set these securely in the Render dashboard
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3 
      
      # Your API key for content generation (set this value on the Render Dashboard)
      - key: GEMINI_API_KEY
        sync: false 
      
      # Your PostgreSQL database connection string (set this value on the Render Dashboard)
      - key: DATABASE_URL 
        sync: false 

      # VUE_APP_API_URL is set dynamically to the Render backend URL 
      # using the relative path '/api' in your JavaScript code (which is correct).
